### ISSUE TITLE
Почему не работает аутентификация по Sandbox токену?

### ISSUE THREAD

**Issue by Flyingfiish** [Tinkoff/invest-api-csharp-sdk#12]
Выдает такую ошибку:

```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      Grpc.Core.RpcException: Status(StatusCode="Unauthenticated", Detail="")
         at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.GetResponseAsync()
         at Tinkoff.InvestApi.Sample.UsersServiceSample.GetUserInfoDescriptionAsync(CancellationToken cancellationToken) in C:\Projects\invest-api-csharp-sdk-main\Tinkoff.InvestApi.Sample\UsersServiceSample.cs:line 17
         at Tinkoff.InvestApi.Sample.AsyncSample.ExecuteAsync(CancellationToken stoppingToken) in C:\Projects\invest-api-csharp-sdk-main\Tinkoff.InvestApi.Sample\AsyncSample.cs:line 18
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

P.S. обычный токен работает

**Comment by Flyingfiish** [comment]
Нашел ответ в #9
